name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: mnk-game
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit black flake8 mypy pytest pytest-cov numpy

      - name: Run Black (Auto-Fix Code Formatting)
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          black .

      - name: Run Flake8 (Linting)
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          flake8 . || true

      - name: Run Mypy (Type Checking)
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          mypy . || true

      - name: Run Tests with Pytest
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          pytest --cov=.

      - name: Commit and Push Changes (if any)
        shell: bash -l {0}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-format & linting fixes by GitHub Actions"
          git push || echo "No changes to commit"
