name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: mnk-game
          auto-activate-base: false

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          python -m pip install --upgrade pip
          pip install black pytest

      - name: Run Black (Auto-Fix Code Formatting)
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          black .

      - name: Commit and Push Changes (if any)
        shell: bash -l {0}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-format fixes by GitHub Actions"
          git push || echo "No changes to commit"

      - name: Run Tests with pytest
        shell: bash -l {0}
        run: |
          conda activate mnk-game
          pytest --tb=short --disable-warnings
